/**
 * Run with `npm test`. "אזל" / "חסום" on the kiosks (lib/kioskSoldOut.ts — the Android till's
 * SoldOutRules, ported once for the Windows and the browser kiosk):
 *
 *  - every case of the shared golden server/tests/fixtures/sold_out_golden.json (the cloud's
 *    sold_out_rules.decide and the till's SoldOutRules.decide give `expect`);
 *  - the kiosk's own use of it (KioskCatalogView.soldOut: the lock, delisted, stock, the blocks by the
 *    kiosk's clock, the next end) — the `soldOut` cases of kiosk_pricing_parity.json, GENERATED by
 *    running the Android engines.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { blockTimeMs, decideSoldOut, itemBlocksOf, kioskSoldOut, nextBlockEndMs, stockLevelsOf, type SoldOutRow } from './kioskSoldOut';

function fixture(name: string): string {
  const candidates = [join(process.cwd(), '..', 'server', 'tests', 'fixtures', name), join(__dirname, '..', '..', 'server', 'tests', 'fixtures', name)];
  const found = candidates.find((p) => existsSync(p));
  assert.ok(found, `${name} not found`);
  return readFileSync(found, 'utf8');
}

type Row = Record<string, unknown>;

describe('sold out / blocked: the shared golden (SoldOutRules.decide)', () => {
  const golden = JSON.parse(fixture('sold_out_golden.json')) as {
    cases: Array<{ name: string; now: string; till: Row; blocks: Row[]; setting: unknown; trackStock: boolean; stock: number | null; expect: { state: string; reason: string | null; block: string | null; overridable: boolean } }>;
  };
  for (const c of golden.cases) {
    it(c.name, () => {
      const d = decideSoldOut(itemBlocksOf(c.blocks), blockTimeMs(c.now)!, { till: c.till, setting: c.setting, trackStock: c.trackStock, stock: c.stock });
      assert.deepEqual({ state: d.state, reason: d.reason, block: d.block?.id ?? null, overridable: d.state === 'sold_out' }, c.expect);
    });
  }
});

describe('sold out on the kiosk (KioskCatalogView.soldOut), the Android engines’ corpus', () => {
  const corpus = JSON.parse(fixture('kiosk_pricing_parity.json').replace(/\r\n/g, '\n')) as {
    soldOut?: Array<{ name: string; now: string; row: SoldOutRow & { blocks: Row[] }; stock: number | null; expected: { soldOut: boolean; decision: { state: string; reason: string | null; blockId: string | null; untilMs: number | null }; nextEndMs: number | null } }>;
  };
  it('has the cases', () => assert.ok((corpus.soldOut?.length ?? 0) >= 20));
  for (const c of corpus.soldOut ?? []) {
    it(c.name, () => {
      const now = blockTimeMs(c.now)!;
      assert.equal(kioskSoldOut(c.row, c.stock, now), c.expected.soldOut, 'soldOut');
      const blocks = itemBlocksOf(c.row.blocks);
      const d = decideSoldOut(blocks, now);
      assert.deepEqual({ state: d.state, reason: d.reason, blockId: d.block?.id ?? null, untilMs: d.untilMs }, c.expected.decision, 'decision');
      assert.equal(nextBlockEndMs(blocks, now), c.expected.nextEndMs, 'next end');
    });
  }
});

describe('the stock endpoint', () => {
  it('levels by product id; a level that is not a number is left out', () => {
    assert.deepEqual(stockLevelsOf({ levels: [{ productId: 'a', onHand: 3 }, { productId: 'b', onHand: '-1.5' }, { productId: 'c', onHand: null }, { onHand: 2 }] }), { a: 3, b: -1.5 });
    assert.deepEqual(stockLevelsOf(null), {});
  });
});
