/**
 * Run with `npm test`. The kiosk pricing parity corpus (server/tests/fixtures/kiosk_pricing_parity.json),
 * GENERATED by running the Android kiosk's engines (pos-android KioskPricingCorpusTest.kt), replayed
 * through the browser kiosk's own path — its catalog (lib/kioskWebCatalog.ts buildWebCatalog: groups
 * up the category tree, meals), the sheet's taps and the meal window (lib/kioskMoney.ts via
 * lib/kioskPricingCorpus.ts), the order's price (priceKioskOrder: promotions, VAT, tip), the basket's
 * words (cartSubLines / receiptSubLines) and the open order the till collects and re-prices
 * (lib/kioskWebOrders.ts: the held sale's units and details, the totals). Every figure to the agora.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildWebCatalog, type WebCatalog } from './kioskWebCatalog';
import { cartSubLines, chosenOptions, defaultPicks, dishOnDefaults, dishUnitAgorot, mealUnitAgorot, picksValid, priceKioskOrder, promotionsOf, receiptSubLines, type ChosenOption } from './kioskMoney';
import {
  KIOSK_PRICING_PARITY_SHA256,
  corpusNow,
  detailsMoney,
  mealAfter,
  optionRow,
  picksAfter,
  scenarioPromotions,
  type Corpus,
  type CorpusBasketLine,
} from './kioskPricingCorpus';
import { heldSaleCodec, openOrderWire, type OpenOrder, type WebOrderLine } from './kioskWebOrders';
import { webMoneyGroup } from './kioskWebService';

type Row = Record<string, unknown>;

function corpusText(): string {
  const name = 'kiosk_pricing_parity.json';
  const candidates = [join(process.cwd(), '..', 'server', 'tests', 'fixtures', name), join(__dirname, '..', '..', 'server', 'tests', 'fixtures', name)];
  const found = candidates.find((p) => existsSync(p));
  assert.ok(found, `${name} not found`);
  return readFileSync(found, 'utf8').replace(/\r\n/g, '\n');
}

const text = corpusText();
const corpus = JSON.parse(text) as Corpus;

/** One basket line as the browser kiosk builds it from its catalog and the customer's taps. */
function webLineOf(cat: WebCatalog, l: CorpusBasketLine) {
  const p = cat.products.find((x) => x.id === l.productId);
  assert.ok(p, `product ${l.productId}`);
  const groupsOf = (id: string) => (cat.groups[id] ?? []).map(webMoneyGroup);
  const base: WebOrderLine = {
    key: l.id, productId: p.id, name: p.name, qty: l.qty, baseAgorot: p.priceAgorot, unitAgorot: p.priceAgorot, options: [], note: null,
    categoryId: p.categoryId, sku: null, barcode: null, imageUrl: null, allergens: [], noDiscount: p.noDiscount,
  };
  const slots = cat.meals[p.id];
  if (slots && slots.length > 0) {
    const priceOf = (id: string) => cat.products.find((x) => x.id === id)!.priceAgorot;
    const { chosen, valid } = mealAfter(slots, l.taps, (id) => dishOnDefaults(priceOf(id), groupsOf(id)) !== null);
    const components = slots.flatMap((s) =>
      chosen[s.id].map((pid) => {
        const groups = groupsOf(pid);
        const options = chosenOptions(groups, Object.fromEntries(groups.map((g) => [g.id, defaultPicks(g)])));
        return { slot: s, product: cat.products.find((x) => x.id === pid)!, upchargeAgorot: s.choices.find((x) => x.productId === pid)!.upchargeAgorot, options };
      }),
    );
    const line: WebOrderLine = {
      ...base,
      unitAgorot: mealUnitAgorot(p.priceAgorot, components),
      meal: {
        components: components.map((c) => ({
          slotId: c.slot.id, slotName: c.slot.name, productId: c.product.id, name: c.product.name, categoryId: c.product.categoryId,
          listPriceAgorot: c.product.priceAgorot, upchargeAgorot: c.upchargeAgorot, options: c.options.map((o) => ({ ...o })),
        })),
      },
    };
    return { added: valid, line, components, options: [] as ChosenOption[], groups: undefined as string[] | undefined };
  }
  const groups = groupsOf(p.id);
  const picks = picksAfter(groups, l.ops);
  const options = chosenOptions(groups, picks);
  return { added: picksValid(groups, picks), line: { ...base, unitAgorot: dishUnitAgorot(p.priceAgorot, options), options: options.map((o) => ({ ...o })) }, components: [], options, groups: groups.map((g) => g.id) };
}

describe('kiosk pricing parity corpus (generated from the Android engines), through the browser kiosk', () => {
  it('is the pinned file', () => {
    assert.equal(corpus.format, 'kiosk-pricing-parity/1');
    assert.ok(corpus.scenarios.length >= 60, 'at least 60 scenarios');
    assert.equal(createHash('sha256').update(text, 'utf8').digest('hex'), KIOSK_PRICING_PARITY_SHA256);
  });

  for (const s of corpus.scenarios) {
    it(s.name, () => {
      const raw = corpus.catalogs[s.catalog];
      const cat = buildWebCatalog({ products: raw.products, categories: raw.categories, menu: raw.menu, machineCatalog: { mode: 'all' } }, {});
      const built = s.basket.map((l) => webLineOf(cat, l));
      // The sheet / the meal window: what is chosen, what it costs, whether it may go in.
      s.expected.lines.forEach((e, i) => {
        const b = built[i];
        assert.equal(b.added, e.added, `${e.id} added`);
        if (e.groups) assert.deepEqual(b.groups, e.groups, `${e.id} groups`);
        if (e.options) assert.deepEqual(b.options.map(optionRow), e.options, `${e.id} options`);
        if (e.components)
          assert.deepEqual(
            b.components.map((c) => ({ slotId: c.slot.id, productId: c.product.id, upchargeAgorot: c.upchargeAgorot, options: c.options.map(optionRow), extrasAgorot: c.upchargeAgorot + c.options.reduce((x, o) => x + o.chargedAgorot, 0) })),
            e.components.map((c) => ({ slotId: c.slotId, productId: c.productId, upchargeAgorot: c.upchargeAgorot, options: c.options, extrasAgorot: c.extrasAgorot })),
            `${e.id} components`,
          );
        assert.equal(b.line.unitAgorot, e.unitAgorot, `${e.id} unit`);
      });
      // The order: what goes in, priced as KioskViewModel.price.
      const lines = built.filter((b) => b.added).map((b) => b.line);
      const order = priceKioskOrder({
        lines: lines.map((l) => ({ id: l.key, productIds: [l.productId], categoryId: l.categoryId, unitAgorot: l.unitAgorot, qty: l.qty, noDiscount: l.noDiscount === true })),
        promotions: promotionsOf(scenarioPromotions(corpus, s)),
        now: corpusNow(s.now),
        vatRate: s.vatRate,
        tip: { tipEnabled: s.tip.enabled, tipOther: s.tip.other },
        tipPercent: s.tip.percent,
        tipOtherAgorot: s.tip.otherAgorot,
      });
      for (const e of s.expected.lines.filter((x) => x.added)) {
        const pl = order.lines.find((x) => x.id === e.id)!;
        assert.deepEqual(
          { gross: pl.grossAgorot, promotion: pl.promotionAgorot, promotionId: pl.promotionId, promotionName: pl.promotionName, total: pl.totalAgorot },
          { gross: e.grossAgorot, promotion: e.promotionAgorot, promotionId: e.promotionId, promotionName: e.promotionName, total: e.totalAgorot },
          `${e.id} priced`,
        );
        // The basket's words, as the Android cart and receipt.
        const b = built[s.basket.findIndex((x) => x.id === e.id)];
        const words = { options: b.options, components: b.components.map((c) => ({ name: c.product.name, upchargeAgorot: c.upchargeAgorot, options: c.options })) };
        assert.deepEqual(cartSubLines(words), e.cartSubLines, `${e.id} cart words`);
        assert.deepEqual(receiptSubLines(words), e.receiptSubLines, `${e.id} receipt words`);
      }
      const x = s.expected;
      assert.deepEqual(order.applied.map((a) => ({ promotionId: a.promotionId, name: a.name, type: a.type, applications: a.applications, discountAgorot: a.discountAgorot })), x.applied, 'applied');
      assert.deepEqual(order.giftOffers.map((g) => ({ promotionId: g.promotionId, productId: g.productId, quantity: g.quantity })), x.giftOffers, 'gift offers');
      assert.deepEqual(order.near.map((h) => ({ promotionId: h.promotionId, kind: h.kind, missingAgorot: h.missingAgorot })), x.near, 'near');
      assert.deepEqual(order.rewardsAvailable.map((h) => ({ promotionId: h.promotionId, kind: h.kind })), x.rewardsAvailable, 'rewards');
      assert.deepEqual(
        { gross: order.grossAgorot, promotion: order.promotionAgorot, total: order.totalAgorot, net: order.netAgorot, vat: order.vatAgorot, tip: order.tipAgorot, due: order.dueAgorot, items: order.itemCount },
        { gross: x.grossAgorot, promotion: x.promotionAgorot, total: x.totalAgorot, net: x.netAgorot, vat: x.vatAgorot, tip: x.tipAgorot, due: x.dueAgorot, items: x.itemCount },
        'totals',
      );

      // The open order the till collects: the same units, details and money the Android till re-prices.
      const shares = new Map(order.lines.map((l) => [l.id, l] as const));
      const priced = lines.map((l) => ({ ...l, promotionAgorot: shares.get(l.key)!.promotionAgorot, promotionId: shares.get(l.key)!.promotionId, promotionName: shares.get(l.key)!.promotionName }));
      const open: OpenOrder = {
        localId: 'o1', createdAtMs: 0, businessDate: s.now.slice(0, 10), serviceType: 'take_away', tableRef: null, fulfillmentMode: 'BON', configVersion: null,
        customerName: null, customerPhone: null, lines: priced, tipAgorot: order.tipAgorot, vouchers: [], pickupNumber: 1, pickupLabel: '1',
        bon: { mode: 'routing', printerId: null, copies: 1 }, kitchenSent: false, cloudState: null, rejected: null,
      };
      const wire = openOrderWire(open);
      assert.equal(wire.totalAgorot, x.totalAgorot, 'open order total');
      assert.equal(wire.dueAgorot, x.dueAgorot, 'open order due');
      const held = JSON.parse(heldSaleCodec('o1', priced)) as { lines: Array<{ id: string; unitPrice: number; details: Row | null }> };
      for (const e of s.expected.lines.filter((l) => l.added)) {
        const h = held.lines.find((l) => l.id === e.id)!;
        assert.equal(h.unitPrice, e.unitAgorot, `${e.id} held unit`);
        assert.deepEqual(detailsMoney(h.details), detailsMoney(e.document!.details), `${e.id} held details`);
      }
    });
  }
});
