// GENERATED by server/scripts/gen_kiosk_layout_data.py from server/tests/fixtures/kiosk_text_registry.json — do not edit.
import type { KioskTextRegistry } from './kioskTexts';

export const KIOSK_TEXT_REGISTRY_DATA: KioskTextRegistry = { version: 1, languages: ['he', 'en', 'ar', 'ru'], placeholders: [], groups: [], texts: [] };
