/**
 * The kiosk pricing parity corpus (server/tests/fixtures/kiosk_pricing_parity.json) as both
 * TypeScript kiosks' tests replay it: the browser kiosk's (lib/kioskPricingParity.test.ts) and the
 * Windows kiosk's (kiosk-desktop test/kioskPricingParity.test.ts). The corpus is GENERATED by running
 * the Android kiosk's engines (pos-android app/src/test/.../KioskPricingCorpusTest.kt); this module
 * only reads it and replays the customer's taps with the shared rules (lib/kioskMoney.ts) — what
 * each host's sheet and meal window do.
 *
 * Pure; no `@/` imports (the node tests compile it alone).
 */

import {
  changePickQty,
  cyclePre,
  defaultMealChoices,
  defaultPicks,
  mealPick,
  mealSlotProblem,
  picksValid,
  togglePick,
  type ChosenOption,
  type LocalDateTime,
  type MealSlot,
  type MenuGroup,
  type OptionPick,
} from './kioskMoney';
import { voucherBenefitOf, voucherStackingOf, type AppliedDiscountVoucher } from './kioskVouchers';

/** The corpus's SHA-256, its line endings read as LF — the same constant as pos-android's KioskPricingCorpusTest.GOLDEN_SHA256. */
export const KIOSK_PRICING_PARITY_SHA256 = '871bece763440a0066ead952942a2242b1057ba09093060d33785aa915444ba4';

type Row = Record<string, unknown>;

export interface CorpusOption {
  groupId: string;
  optionId: string;
  qty: number;
  pre: string | null;
  priceAgorot: number;
  chargedAgorot: number;
}

export interface CorpusBasketLine {
  id: string;
  productId: string;
  qty: number;
  /** The sheet's taps after the defaults: ["toggle", g, o] / ["qty", g, o, ±n] / ["pre", g, o]. */
  ops?: Array<[string, string, string, number?]>;
  /** The meal window's slot taps after the defaults: [slotId, productId]. */
  taps?: Array<[string, string]>;
  /** A component's own required choice answered in the meal window: [slotId, productId, "toggle", groupId, optionId]. */
  componentOps?: Array<[string, string, string, string, string]>;
}

export interface CorpusLine {
  id: string;
  added: boolean;
  groups?: string[];
  options?: CorpusOption[];
  components?: Array<{ slotId: string; productId: string; upchargeAgorot: number; extrasAgorot: number; options: CorpusOption[] }>;
  unitAgorot: number;
  qty?: number;
  grossAgorot?: number;
  promotionAgorot?: number;
  promotionId?: string | null;
  promotionName?: string | null;
  totalAgorot?: number;
  cartSubLines?: string[];
  receiptSubLines?: Array<[string, number | null]>;
  /** The sale document's item (SaleRepository.buildItems, the push payload's names). */
  document?: { unitPrice: number; totalPrice: number; promotionDiscount: number | null; promotionId: string | null; promotionName: string | null; noDiscount: number; details: Row | null };
}

export interface CorpusScenario {
  name: string;
  tags: string[];
  catalog: string;
  /** The device's local time, "yyyy-MM-ddTHH:mm". */
  now: string;
  vatRate: number;
  tip: { enabled: boolean; other: boolean; percent: number | null; otherAgorot: number | null };
  promotions: string[];
  basket: CorpusBasketLine[];
  expected: {
    lines: CorpusLine[];
    applied: Array<{ promotionId: string; name: string; type: string; applications: number; discountAgorot: number }>;
    giftOffers: Array<{ promotionId: string; productId: string; quantity: number }>;
    near: Array<{ promotionId: string; kind: string; missingAgorot: number }>;
    rewardsAvailable: Array<{ promotionId: string; kind: string }>;
    grossAgorot: number;
    promotionAgorot: number;
    totalAgorot: number;
    netAgorot: number;
    vatAgorot: number;
    tipAgorot: number;
    dueAgorot: number;
    itemCount: number;
    /** The sale document's money (buildTransaction): shekels, as the push payload carries them. */
    document: { documentDiscount: number | null; netAmount: number; vatAmount: number; tipAmount: number; promotions: Row[] | null };
  };
}

/** A discount voucher the cloud holds for the order, as the corpus names it (what `reserve` answered, with the lookup's `benefit`). */
export interface CorpusVoucherSpec {
  voucherId: string;
  batchId: string;
  serial: number;
  batchName: string;
  stacking: string;
  uses: number;
  benefit: Row;
}

/** "שוברי הנחה": the basket as the promotions priced it, then the vouchers in the order applied (Cart.withVoucherDiscounts). */
export interface CorpusVoucherCase {
  name: string;
  tags: string[];
  catalog: string;
  now: string;
  vatRate: number;
  tipPercent: number | null;
  promotions: string[];
  basket: CorpusBasketLine[];
  vouchers: CorpusVoucherSpec[];
  expected: {
    outcomes: Array<{ voucherId: string; amountAgorot: number; shares: Record<string, number>; skipped: Array<[string, string]>; refusal: string | null }>;
    lines: Array<{ id: string; unitAgorot: number; grossAgorot: number; promotionAgorot: number; promotionYieldedAgorot: number; voucherAgorot: number; totalAgorot: number }>;
    applied: Array<{ promotionId: string; name: string; type: string; applications: number; discountAgorot: number }>;
    grossAgorot: number;
    promotionAgorot: number;
    voucherAgorot: number;
    totalAgorot: number;
    netAgorot: number;
    vatAgorot: number;
    tipAgorot: number;
    dueAgorot: number;
    itemCount: number;
    /** The sale document's fields (buildTransaction / buildItems, shekels): the discount, the items' shares, `voucherDiscounts[]` (an item's id is its basket line's). */
    document: {
      documentDiscount: number | null;
      netAmount: number;
      vatAmount: number;
      tipAmount: number;
      promotions: Row[] | null;
      items: Array<{ id: string; promotionDiscount: number | null; promotionId: string | null; voucherDiscount: number | null }>;
      voucherDiscounts: Row[] | null;
    };
  };
}

/** "שובר פריטים" as a leg of the payment: what each voucher is worth against the priced basket, the marks it leaves, what is left to pay. */
export interface CorpusGoodsCase {
  name: string;
  tags: string[];
  catalog: string;
  promotions: string[];
  tipPercent: number | null;
  basket: CorpusBasketLine[];
  vouchers: CorpusVoucherSpec[];
  legs: Array<{ serial: number; includeExtras: boolean; redeemed: Array<[string, number]> }>;
  expected: {
    legs: Array<{ serial: number; valueAgorot: number; amountAgorot: number }>;
    /** By basket line: the note a covered line carries ("כלול בשובר #7 (1)"), null when none. */
    notes: Record<string, string | null>;
    totalAgorot: number;
    tipAgorot: number;
    goodsDueAgorot: number;
    dueAgorot: number;
  };
}

export interface Corpus {
  format: string;
  catalogs: Record<string, { categories: Row[]; products: Row[]; menu: Row }>;
  promotionLibrary: Row[];
  scenarios: CorpusScenario[];
  vouchers?: CorpusVoucherCase[];
  goodsVouchers?: CorpusGoodsCase[];
}

/** The discount voucher of a corpus case as the kiosks hold it for an order (AppliedVoucher). */
export function appliedVoucherOf(v: CorpusVoucherSpec): AppliedDiscountVoucher {
  const benefit = voucherBenefitOf(v.benefit);
  if (!benefit) throw new Error(`voucher ${v.voucherId}: no benefit`);
  return {
    reservationId: `r-${v.voucherId}`,
    clientRequestId: `c-${v.voucherId}`,
    voucherId: v.voucherId,
    code: `CODE-${v.voucherId}`,
    serial: v.serial,
    batchId: v.batchId,
    batchName: v.batchName,
    stacking: voucherStackingOf(v.stacking),
    benefit,
    uses: v.uses,
    expiresAt: null,
  };
}

/** The scenario's promotions, as the cloud sends them, in the scenario's order. */
export function scenarioPromotions(corpus: Corpus, s: Pick<CorpusScenario, 'promotions'>): Row[] {
  const library = new Map(corpus.promotionLibrary.map((p) => [String(p.id), p] as const));
  return s.promotions.map((id) => library.get(id)).filter((p): p is Row => !!p);
}

/** "2026-10-08T13:00" as the promotions' clock. */
export function corpusNow(s: string): LocalDateTime {
  return { date: s.slice(0, 10), hour: Number(s.slice(11, 13)), minute: Number(s.slice(14, 16)) };
}

/** The same moment as a local Date (the Windows main process reads `new Date()`). */
export function corpusDate(s: string): Date {
  return new Date(Number(s.slice(0, 4)), Number(s.slice(5, 7)) - 1, Number(s.slice(8, 10)), Number(s.slice(11, 13)), Number(s.slice(14, 16)));
}

/** The sheet's taps from each group's defaults (DishDraft.start → toggle / changeQty / cyclePre); a tap on a group the dish lacks does nothing. */
export function picksAfter(groups: readonly MenuGroup[], ops: CorpusBasketLine['ops']): Record<string, OptionPick[]> {
  const picks: Record<string, OptionPick[]> = Object.fromEntries(groups.map((g) => [g.id, defaultPicks(g)]));
  for (const [op, gid, oid, delta] of ops ?? []) {
    const g = groups.find((x) => x.id === gid);
    if (!g) continue;
    if (op === 'toggle') picks[g.id] = togglePick(g, picks[g.id], oid);
    else if (op === 'qty') picks[g.id] = changePickQty(g, picks[g.id], oid, delta ?? 0);
    else if (op === 'pre') picks[g.id] = cyclePre(g, picks[g.id], oid);
    else throw new Error(`unknown op ${op}`);
  }
  return picks;
}

/**
 * The meal window's taps from each slot's defaults (MealDraft.start → pick), then the components' own
 * answers (MealDraft.updateDish → toggle); whether it may go in (MealDraft.isValid). `groupsOf`: a
 * component's groups; each component's picks start on their defaults.
 */
export function mealAfter(
  slots: readonly MealSlot[],
  line: Pick<CorpusBasketLine, 'taps' | 'componentOps'>,
  groupsOf: (productId: string) => MenuGroup[],
): { chosen: Record<string, string[]>; picks: (slotId: string, productId: string) => Record<string, OptionPick[]>; valid: boolean } {
  const chosen: Record<string, string[]> = Object.fromEntries(slots.map((s) => [s.id, defaultMealChoices(s)]));
  for (const [slotId, productId] of line.taps ?? []) {
    const s = slots.find((x) => x.id === slotId);
    if (s) chosen[s.id] = mealPick(s, chosen[s.id], productId);
  }
  const answered: Record<string, Record<string, OptionPick[]>> = {};
  const picks = (slotId: string, productId: string) =>
    answered[`${slotId}:${productId}`] ?? Object.fromEntries(groupsOf(productId).map((g) => [g.id, defaultPicks(g)]));
  for (const [slotId, productId, op, groupId, optionId] of line.componentOps ?? []) {
    if (op !== 'toggle') throw new Error(`unknown op ${op}`);
    const g = groupsOf(productId).find((x) => x.id === groupId);
    if (!g) continue;
    const now = picks(slotId, productId);
    answered[`${slotId}:${productId}`] = { ...now, [g.id]: togglePick(g, now[g.id] ?? [], optionId) };
  }
  const valid = !slots.some((s) => mealSlotProblem(s, chosen[s.id], (pid) => picksValid(groupsOf(pid), picks(s.id, pid))));
  return { chosen, picks, valid };
}

export function optionRow(o: Pick<ChosenOption, 'groupId' | 'optionId' | 'qty' | 'pre' | 'priceAgorot' | 'chargedAgorot'>): CorpusOption {
  return { groupId: o.groupId, optionId: o.optionId, qty: o.qty, pre: o.pre, priceAgorot: o.priceAgorot, chargedAgorot: o.chargedAgorot };
}

/** The money of a line's details (LineDetailsCodec, shekels): what a till or the cloud prices the line from. */
export function detailsMoney(d: Row | null | undefined) {
  if (!d) return null;
  const mods = (list: unknown) =>
    ((list as Row[] | undefined) ?? []).map((m) => ({ groupId: m.groupId, optionId: m.optionId, qty: m.qty, pre: m.pre ?? null, price: m.price, charged: m.charged }));
  const meal = d.meal as Row | undefined;
  const modifiers = mods(d.modifiers);
  const components = meal
    ? ((meal.components as Row[]) ?? []).map((c) => ({ slotId: c.slotId, productId: c.productId, listPrice: c.listPrice, qty: c.qty, upcharge: c.upcharge, modifiers: mods(c.modifiers) }))
    : [];
  // A dish with nothing chosen is a plain line on either side.
  if (modifiers.length === 0 && components.length === 0) return null;
  return { basePrice: d.basePrice, modifiers, components };
}
