// GENERATED by server/scripts/gen_kiosk_layout_data.py from server/tests/fixtures/kiosk_category_icons.json — do not edit.
import type { KioskIconSet } from './kioskIcons';

export const KIOSK_ICON_DATA: KioskIconSet = { version: 1, viewBox: 24, icons: [], cases: [] };
