/**
 * Run with `npm test`. The vouchers sections of the kiosk pricing parity corpus (server/tests/fixtures/kiosk_pricing_parity.json,
 * GENERATED by running the Android kiosk's engines — pos-android KioskPricingCorpusTest.kt) through the browser kiosk's own path:
 *
 *  - "vouchers": the basket as the promotions priced it, then the discount vouchers in the order applied
 *    (`Cart.withPromotions(..).withVoucherDiscounts()` ↔ lib/kioskMoney.ts priceKioskOrder with `vouchers`): what each took,
 *    from which lines, the lines it left out and why, a promotion that gave way to a voucher, the totals, the VAT and the tip
 *    on what is left, and the fields the sale document carries (`items[].voucherDiscount`, `voucherDiscounts[]`);
 *  - "goodsVouchers": a goods voucher as a leg of the payment (`coverByVoucher` ↔ lib/kioskWebOrders.ts coverLegs / recountLegs):
 *    what each is worth against the priced basket, the notes it leaves on the lines, what is left to pay.
 *
 * (The Windows kiosk replays the same sections through its main process: kiosk-desktop/test/kioskVoucherParity.test.ts.)
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildWebCatalog, type WebCatalog } from './kioskWebCatalog';
import { chosenOptions, dishUnitAgorot, mealUnitAgorot, picksValid, priceKioskOrder, promotionsOf, type ChosenOption } from './kioskMoney';
import { appliedVoucherOf, corpusNow, mealAfter, picksAfter, scenarioPromotions, type Corpus, type CorpusBasketLine, type CorpusGoodsCase, type CorpusVoucherCase } from './kioskPricingCorpus';
import { coverLegs, dueAgorot, legMarks, recountLegs, type CoverLine, type VoucherLeg, type WebOrderLine } from './kioskWebOrders';
import { voucherDiscountsWire } from './kioskVouchers';
import { webMoneyGroup } from './kioskWebService';

function corpusText(): string {
  const name = 'kiosk_pricing_parity.json';
  const candidates = [join(process.cwd(), '..', 'server', 'tests', 'fixtures', name), join(__dirname, '..', '..', 'server', 'tests', 'fixtures', name)];
  const found = candidates.find((p) => existsSync(p));
  assert.ok(found, `${name} not found`);
  return readFileSync(found, 'utf8').replace(/\r\n/g, '\n');
}

const corpus = JSON.parse(corpusText()) as Corpus;

/** One basket line as the browser kiosk builds it from its catalog and the customer's taps (as kioskPricingParity.test.ts). */
function webLineOf(cat: WebCatalog, l: CorpusBasketLine): { added: boolean; line: WebOrderLine } {
  const p = cat.products.find((x) => x.id === l.productId);
  assert.ok(p, `product ${l.productId}`);
  const groupsOf = (id: string) => (cat.groups[id] ?? []).map(webMoneyGroup);
  const base: WebOrderLine = {
    key: l.id, productId: p.id, name: p.name, qty: l.qty, baseAgorot: p.priceAgorot, unitAgorot: p.priceAgorot, options: [], note: null,
    categoryId: p.categoryId, sku: null, barcode: null, imageUrl: null, allergens: [], noDiscount: p.noDiscount,
  };
  const slots = cat.meals[p.id];
  if (slots && slots.length > 0) {
    const { chosen, picks, valid } = mealAfter(slots, l, groupsOf);
    const components = slots.flatMap((s) =>
      chosen[s.id].map((pid) => {
        const options = chosenOptions(groupsOf(pid), picks(s.id, pid));
        return { upchargeAgorot: s.choices.find((x) => x.productId === pid)!.upchargeAgorot, options };
      }),
    );
    return { added: valid, line: { ...base, unitAgorot: mealUnitAgorot(p.priceAgorot, components) } };
  }
  const groups = groupsOf(p.id);
  const picks = picksAfter(groups, l.ops);
  const options: ChosenOption[] = chosenOptions(groups, picks);
  return { added: picksValid(groups, picks), line: { ...base, unitAgorot: dishUnitAgorot(p.priceAgorot, options) } };
}

function basketOf(c: Pick<CorpusVoucherCase, 'catalog' | 'basket'>) {
  const raw = corpus.catalogs[c.catalog];
  const cat = buildWebCatalog({ products: raw.products, categories: raw.categories, menu: raw.menu, machineCatalog: { mode: 'all' } }, {});
  return c.basket.map((l) => webLineOf(cat, l)).filter((b) => b.added).map((b) => b.line);
}

const promoLines = (lines: readonly WebOrderLine[]) =>
  lines.map((l) => ({ id: l.key, productIds: [l.productId], categoryId: l.categoryId, unitAgorot: l.unitAgorot, qty: l.qty, noDiscount: l.noDiscount === true }));

describe('the vouchers sections of the corpus are the pinned file\'s', () => {
  it('has them (discount vouchers, goods vouchers)', () => {
    assert.ok((corpus.vouchers?.length ?? 0) >= 15, 'discount voucher cases');
    assert.ok((corpus.goodsVouchers?.length ?? 0) >= 8, 'goods voucher cases');
  });
});

describe('discount vouchers (corpus "vouchers", generated from the Android engines), through the browser kiosk', () => {
  for (const c of corpus.vouchers ?? []) {
    it(c.name, () => {
      const lines = basketOf(c);
      const order = priceKioskOrder({
        lines: promoLines(lines),
        promotions: promotionsOf(scenarioPromotions(corpus, c)),
        now: corpusNow(c.now),
        vatRate: c.vatRate,
        tip: { tipEnabled: c.tipPercent !== null, tipOther: false },
        tipPercent: c.tipPercent,
        vouchers: c.vouchers.map(appliedVoucherOf),
      });
      const x = c.expected;
      // What each voucher took, from which lines, and the lines it left out and why.
      assert.equal(order.voucherOutcomes.length, x.outcomes.length);
      x.outcomes.forEach((e, i) => {
        const o = order.voucherOutcomes[i];
        assert.equal(o.voucher.voucherId, e.voucherId);
        assert.equal(o.amountAgorot, e.amountAgorot, `${e.voucherId} amount`);
        assert.deepEqual(o.shares, e.shares, `${e.voucherId} shares`);
        assert.deepEqual(o.skipped, e.skipped, `${e.voucherId} skipped`);
        assert.equal(o.refusal, e.refusal, `${e.voucherId} refusal`);
      });
      // Each line: the promotion's share (less what gave way to a voucher), the vouchers' share, what it costs.
      for (const e of x.lines) {
        const l = order.lines.find((y) => y.id === e.id)!;
        assert.deepEqual(
          { unit: l.unitAgorot, gross: l.grossAgorot, promotion: l.promotionAgorot, yielded: l.promotionYieldedAgorot, voucher: l.voucherAgorot, total: l.totalAgorot },
          { unit: e.unitAgorot, gross: e.grossAgorot, promotion: e.promotionAgorot, yielded: e.promotionYieldedAgorot, voucher: e.voucherAgorot, total: e.totalAgorot },
          `${e.id} line`,
        );
      }
      assert.deepEqual(order.applied.map((a) => ({ promotionId: a.promotionId, name: a.name, type: a.type, applications: a.applications, discountAgorot: a.discountAgorot })), x.applied);
      assert.deepEqual(
        { gross: order.grossAgorot, promotion: order.promotionAgorot, voucher: order.voucherAgorot, total: order.totalAgorot, net: order.netAgorot, vat: order.vatAgorot, tip: order.tipAgorot, due: order.dueAgorot, items: order.itemCount },
        { gross: x.grossAgorot, promotion: x.promotionAgorot, voucher: x.voucherAgorot, total: x.totalAgorot, net: x.netAgorot, vat: x.vatAgorot, tip: x.tipAgorot, due: x.dueAgorot, items: x.itemCount },
      );
      // The sale document's fields: the discount (every share), each item's shares, the vouchers with their lines.
      const d = x.document;
      assert.equal(order.promotionAgorot + order.voucherAgorot > 0 ? (order.promotionAgorot + order.voucherAgorot) / 100 : null, d.documentDiscount);
      assert.equal(order.netAgorot / 100, d.netAmount);
      assert.equal(order.vatAgorot / 100, d.vatAmount);
      assert.deepEqual(
        d.items.map((i) => {
          const l = order.lines.find((y) => y.id === i.id)!;
          return { id: i.id, promotionDiscount: l.promotionAgorot > 0 ? l.promotionAgorot / 100 : null, promotionId: l.promotionAgorot > 0 ? l.promotionId : null, voucherDiscount: l.voucherAgorot > 0 ? l.voucherAgorot / 100 : null };
        }),
        d.items,
      );
      const wire = voucherDiscountsWire(order.voucherOutcomes, (id) => id, (a) => a / 100);
      assert.deepEqual(wire.length > 0 ? wire : null, d.voucherDiscounts);
    });
  }
});

describe('goods vouchers as legs of the payment (corpus "goodsVouchers", generated from the Android engines), through the browser kiosk', () => {
  for (const c of (corpus.goodsVouchers ?? []) as CorpusGoodsCase[]) {
    it(c.name, () => {
      const lines = basketOf(c);
      const order = priceKioskOrder({
        lines: promoLines(lines),
        promotions: promotionsOf(scenarioPromotions(corpus, c)),
        now: corpusNow('2026-10-08T13:00'),
        vatRate: 0.18,
        tip: { tipEnabled: c.tipPercent !== null, tipOther: false },
        tipPercent: c.tipPercent,
        vouchers: c.vouchers.map(appliedVoucherOf),
      });
      // The basket as the goods vouchers read it: each line's dish price, and the shares taken off it.
      const cover: CoverLine[] = order.lines.map((l) => {
        const w = lines.find((y) => y.key === l.id)!;
        return { key: l.id, productId: w.productId, qty: l.qty, unitAgorot: l.unitAgorot, baseAgorot: w.baseAgorot, promotionAgorot: l.promotionAgorot, voucherAgorot: l.voucherAgorot };
      });
      const legs: VoucherLeg[] = c.legs.map((l) => ({
        redemptionId: `r${l.serial}`, serial: l.serial, amountAgorot: 0, eventName: null, includeExtras: l.includeExtras,
        redeemed: l.redeemed.map(([productId, quantity]) => ({ productId, tillProductId: null, name: null, quantity })),
      }));
      const x = c.expected;
      const values = coverLegs(cover, legs).values;
      const done = recountLegs(cover, legs);
      assert.deepEqual(
        done.map((l, i) => ({ serial: l.serial, valueAgorot: values[i], amountAgorot: l.amountAgorot })),
        x.legs,
        'legs',
      );
      assert.deepEqual(Object.fromEntries(c.basket.filter((b) => cover.some((l) => l.key === b.id)).map((b) => [b.id, legMarks(cover, legs).get(b.id) ?? null])), x.notes, 'notes');
      assert.equal(order.totalAgorot, x.totalAgorot);
      assert.equal(order.tipAgorot, x.tipAgorot);
      const goodsDue = Math.max(0, order.totalAgorot - done.reduce((s, l) => s + l.amountAgorot, 0));
      assert.equal(goodsDue, x.goodsDueAgorot);
      // What is left to pay: the goods and the tip less the legs — what the card is asked.
      assert.equal(dueAgorot(order.totalAgorot, order.tipAgorot, done), x.dueAgorot);
    });
  }
});
