/**
 * The kiosk pricing parity corpus (pos-server server/tests/fixtures/kiosk_pricing_parity.json) through
 * the Windows kiosk. The corpus is GENERATED by running the Android kiosk's engines (pos-android
 * KioskPricingCorpusTest.kt); here every scenario goes the Windows kiosk's own way, to the agora:
 *
 *  - its catalog (main/kiosk/catalog.ts buildKioskCatalog — groups up the category tree, meals) and
 *    the customer's taps on its sheet and meal window (client lib/kioskMoney.ts, replayed by
 *    lib/kioskPricingCorpus.ts);
 *  - the main process's re-pricing of the basket it is sent (KioskService.priceBasket: choices,
 *    meals, promotions by the kiosk's clock), the document's totals and tip (core/sale.ts);
 *  - the fiscal document it issues (main/fiscal/ledger.ts documentWire): each item's unit, gross,
 *    promotion share and details money, the document's discount, net, VAT, tip and promotions — the
 *    fields the Android till's push payload carries for the same sale.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { chosenOptions, picksValid } from '@dash-lib/kioskMoney';
import {
  KIOSK_PRICING_PARITY_SHA256,
  corpusDate,
  detailsMoney,
  mealAfter,
  optionRow,
  picksAfter,
  scenarioPromotions,
  type Corpus,
  type CorpusScenario,
} from '@dash-lib/kioskPricingCorpus';
import { moneyGroupOf, type KioskCatalogData } from '../src/main/kiosk/catalog';
import { saleTotals, tipToCharge, unitAgorot, type SaleLine } from '../src/core/sale';
import { documentWire, type DocDraft } from '../src/main/fiscal/ledger';
import { KioskService } from '../src/main/service';
import type { BasketChange, StartPaymentIn } from '../src/shared/bridge';
import type { Transport } from '../src/main/printer/transports';

const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const FIXTURE = path.join(here, '..', '..', 'server', 'tests', 'fixtures', 'kiosk_pricing_parity.json');

type Row = Record<string, unknown>;
type Applied = { promotionId: string; name: string; type: string; applications: number; discountAgorot: number };
type Priced = { lines: SaleLine[]; changes: BasketChange[]; promotions: Applied[] };
const noPrinter: Transport = { send: async () => undefined, status: async () => ({ health: 'ok', detail: null }), list: async () => [], dispose: () => undefined };
const r2 = (agorot: number) => Math.round(agorot) / 100;

describe.runIf(existsSync(FIXTURE))('the kiosk pricing parity corpus (Android engines), through the Windows kiosk', () => {
  const text = existsSync(FIXTURE) ? readFileSync(FIXTURE, 'utf8').replace(/\r\n/g, '\n') : '{"scenarios":[]}';
  const corpus = JSON.parse(text) as Corpus;

  it('is the pinned file, generated from the Android engines', () => {
    expect(corpus.format).toBe('kiosk-pricing-parity/1');
    expect(corpus.scenarios.length).toBeGreaterThanOrEqual(60);
    expect(createHash('sha256').update(text, 'utf8').digest('hex')).toBe(KIOSK_PRICING_PARITY_SHA256);
  });

  function kiosk(s: CorpusScenario) {
    const svc = new KioskService({ dataDir: mkdtempSync(path.join(os.tmpdir(), 'kd-parity-')), appVersion: '0.3.0', deviceInfo: {}, transport: noPrinter, downloader: async () => { throw new Error('no media'); } });
    const raw = corpus.catalogs[s.catalog];
    svc.cloud.applyCatalog({ syncType: 'full', products: raw.products, categories: raw.categories, menu: raw.menu, machineCatalog: { mode: 'all' }, serverTime: 'x' });
    svc.cloud.setPromotions(scenarioPromotions(corpus, s), null);
    return svc;
  }

  /** What the Windows screens send for each line the customer could add (the sheet's and the meal window's own rules). */
  function screenLines(cat: KioskCatalogData, s: CorpusScenario) {
    const groupsOf = (id: string) => (cat.groups[id] ?? []).map(moneyGroupOf);
    return s.basket.map((l) => {
      const slots = cat.meals[l.productId];
      if (slots && slots.length > 0) {
        const { chosen, picks, valid } = mealAfter(slots, l, groupsOf);
        // Each component with its choices, as the meal window sends them (preview-dish.ts orderMealOf).
        const components = slots.flatMap((sl) =>
          chosen[sl.id].map((productId) => ({
            slotId: sl.id,
            productId,
            options: chosenOptions(groupsOf(productId), picks(sl.id, productId)).map((o) => ({ groupId: o.groupId, optionId: o.optionId, qty: o.qty, pre: o.pre })),
          })),
        );
        return { added: valid, input: { key: l.id, productId: l.productId, qty: l.qty, notes: [], options: [], meal: { components } } };
      }
      const groups = groupsOf(l.productId);
      const picks = picksAfter(groups, l.ops);
      const options = chosenOptions(groups, picks).map((o) => ({ groupId: o.groupId, optionId: o.optionId, qty: o.qty, pre: o.pre }));
      return { added: picksValid(groups, picks), input: { key: l.id, productId: l.productId, qty: l.qty, notes: [], options } };
    });
  }

  for (const s of corpus.scenarios) {
    it(s.name, () => {
      const svc = kiosk(s);
      try {
        const cat = (svc as unknown as { catalogData(): KioskCatalogData }).catalogData();
        const screen = screenLines(cat, s);
        expect(screen.map((x) => x.added)).toEqual(s.expected.lines.map((e) => e.added));
        const input: StartPaymentIn = {
          service: 'take_away', customerName: null, customerPhone: null, tableRef: null,
          tipPct: s.tip.percent, tipAgorot: s.tip.otherAgorot,
          lines: screen.filter((x) => x.added).map((x) => x.input) as StartPaymentIn['lines'],
        };
        const { lines, changes, promotions } = (svc as unknown as { priceBasket(i: StartPaymentIn, now: Date): Priced }).priceBasket(input, corpusDate(s.now));
        expect(changes).toEqual([]);
        const x = s.expected;
        for (const e of x.lines.filter((l) => l.added)) {
          const l = lines.find((y) => y.key === e.id)!;
          expect(unitAgorot(l), `${e.id} unit`).toBe(e.unitAgorot);
          if (e.options) expect(l.options.map((o) => optionRow({ ...o, pre: o.pre ?? null, chargedAgorot: o.chargedAgorot ?? 0 })), `${e.id} options`).toEqual(e.options);
          if (e.components)
            expect(
              l.meal!.components.map((c) => ({ slotId: c.slotId, productId: c.productId, upchargeAgorot: c.upchargeAgorot, options: c.options.map((o) => optionRow({ ...o, pre: o.pre ?? null, chargedAgorot: o.chargedAgorot ?? 0 })) })),
              `${e.id} components`,
            ).toEqual(e.components.map((c) => ({ slotId: c.slotId, productId: c.productId, upchargeAgorot: c.upchargeAgorot, options: c.options })));
          expect({ promotion: l.promotionAgorot ?? 0, promotionId: l.promotionId ?? null }, `${e.id} promotion`).toEqual({ promotion: e.promotionAgorot, promotionId: e.promotionId });
        }
        expect(promotions).toEqual(x.applied);
        const goods = saleTotals(lines, s.vatRate);
        const tip = tipToCharge({ tipEnabled: s.tip.enabled, tipOther: s.tip.other }, goods.totalAgorot, s.tip.percent, s.tip.otherAgorot);
        const totals = saleTotals(lines, s.vatRate, tip);
        expect({ gross: totals.grossAgorot, discount: totals.discountAgorot, total: totals.totalAgorot, net: totals.netAgorot, vat: totals.vatAgorot, tip: totals.tipAgorot, due: totals.chargeAgorot }).toEqual({
          gross: x.grossAgorot, discount: x.promotionAgorot, total: x.totalAgorot, net: x.netAgorot, vat: x.vatAgorot, tip: x.tipAgorot, due: x.dueAgorot,
        });
        if (lines.length === 0) return;

        // The fiscal document: what the Android till's push payload carries for the same sale.
        const wire = documentWire(draft(lines, promotions, totals));
        const items = wire.items as Row[];
        x.lines.filter((l) => l.added).forEach((e, i) => {
          const item = items[i];
          const d = e.document!;
          expect({ unitPrice: item.unitPrice, totalPrice: item.totalPrice, promotionDiscount: item.promotionDiscount ?? null, promotionId: item.promotionId ?? null }, `${e.id} item`).toEqual({
            unitPrice: d.unitPrice, totalPrice: d.totalPrice, promotionDiscount: d.promotionDiscount, promotionId: d.promotionId,
          });
          expect(detailsMoney(item.details as Row | undefined), `${e.id} details`).toEqual(detailsMoney(d.details));
        });
        expect({ documentDiscount: wire.documentDiscount ?? null, netAmount: wire.netAmount, vatAmount: wire.vatAmount, tipAmount: wire.tipAmount }).toEqual({
          documentDiscount: x.document.documentDiscount, netAmount: x.document.netAmount, vatAmount: x.document.vatAmount, tipAmount: x.document.tipAmount,
        });
        expect((wire.promotions as Row[] | undefined) ?? null).toEqual(x.document.promotions);
        // The card leg is the goods; the tip rides beside it (the cloud refuses legs that do not sum).
        expect(((wire.payments as Row[])[0] as Row).amount).toBe(r2(totals.totalAgorot));
      } finally {
        svc.stop();
      }
    });
  }
});

describe.runIf(existsSync(FIXTURE))('"אזל" / "חסום" (the corpus sold-out cases), through the Windows kiosk catalog', () => {
  const text = existsSync(FIXTURE) ? readFileSync(FIXTURE, 'utf8') : '{}';
  const cases = ((JSON.parse(text) as { soldOut?: Array<{ name: string; now: string; row: Row; stock: number | null; expected: { soldOut: boolean } }> }).soldOut ?? []);
  for (const c of cases) {
    it(c.name, () => {
      const svc = new KioskService({ dataDir: mkdtempSync(path.join(os.tmpdir(), 'kd-soldout-')), appVersion: '0.3.0', deviceInfo: {}, transport: noPrinter, downloader: async () => { throw new Error('no media'); } });
      try {
        const row: Row = { ...c.row, id: 'p1', name: 'פריט', price: 10, categoryId: 'c1' };
        svc.cloud.applyCatalog({ syncType: 'full', products: [row], categories: [{ id: 'c1', name: 'c1', isActive: true }], menu: null, machineCatalog: { mode: 'all' }, serverTime: 'x' });
        if (c.stock !== null) svc.cloud.mergeStockLevels({ p1: c.stock });
        const realNow = Date.now;
        Date.now = () => Date.parse(c.now);
        try {
          const cat = (svc as unknown as { catalogData(): KioskCatalogData }).catalogData();
          const p = cat.products.find((x) => x.id === 'p1');
          // Delisted: not on the kiosk at all (sellableOnKiosk); else shown greyed or hidden by soldOutMode.
          if (row.inStock === false) expect(p).toBeUndefined();
          else expect(p?.soldOut).toBe(c.expected.soldOut);
        } finally {
          Date.now = realNow;
        }
      } finally {
        svc.stop();
      }
    });
  }
});

function draft(lines: SaleLine[], promotions: Applied[], totals: ReturnType<typeof saleTotals>): DocDraft {
  return {
    id: '00000000-0000-4000-8000-000000000001',
    documentType: 320,
    number: 1,
    prefix: null,
    status: 'completed',
    createdAt: '',
    updatedAt: '',
    shiftId: 's',
    businessDate: '2026-10-08',
    cashierId: 'kiosk:m',
    cashierName: 'קיוסק',
    branchId: null,
    orderId: null,
    lines,
    itemIds: lines.map((_, i) => `00000000-0000-4000-8000-0000000000${String(i).padStart(2, '0')}`),
    tracked: [],
    totals,
    promotions,
    card: { brand: 'visa', last4: '1', authNum: '1', uid: 'u', payments: null, firstPaymentAgorot: null, chargedAgorot: totals.chargeAgorot, meta: {} } as unknown as DocDraft['card'],
    paymentId: 'p',
    voidMeta: null,
  };
}
