/**
 * The vouchers sections of the kiosk pricing parity corpus (pos-server server/tests/fixtures/kiosk_pricing_parity.json, GENERATED by
 * running the Android kiosk's engines — pos-android KioskPricingCorpusTest.kt) through the Windows kiosk's main process:
 *
 *  - "vouchers": the discount vouchers ("שוברי הנחה") held for the order, applied after the promotions in the order taken
 *    (`Cart.withPromotions(..).withVoucherDiscounts()` ↔ KioskService.priceBasket): what each took and from which lines, the
 *    lines it left out and why, a promotion that gave way to a voucher, the totals, the VAT and the tip on what is left, and the
 *    fiscal document it issues (ledger.ts documentWire: `items[].voucherDiscount`, `voucherDiscounts[]`, inside the discount);
 *  - "goodsVouchers": a goods voucher as a leg of the payment (`coverByVoucher` ↔ KioskService.legsOf): what each is worth
 *    against the priced basket, the marks it leaves on the document's lines, what is left for the card — and the document's
 *    `production_voucher` legs and the card for the rest (the cloud refuses legs that do not sum).
 *
 * (The browser kiosk replays the same sections through its own path: client/src/lib/kioskVoucherParity.test.ts.)
 */

import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { chosenOptions, picksValid } from '@dash-lib/kioskMoney';
import { appliedVoucherOf, corpusDate, mealAfter, picksAfter, scenarioPromotions, type Corpus, type CorpusBasketLine, type CorpusGoodsCase, type CorpusVoucherCase } from '@dash-lib/kioskPricingCorpus';
import { moneyGroupOf, type KioskCatalogData } from '../src/main/kiosk/catalog';
import { lineGross, saleTotals, tipToCharge, unitAgorot, type SaleLine } from '../src/core/sale';
import { documentWire, docVoucherDiscounts, type DocDraft, type DocVoucherLeg } from '../src/main/fiscal/ledger';
import { KioskService } from '../src/main/service';
import type { BasketChange, StartPaymentIn } from '../src/shared/bridge';
import type { Transport } from '../src/main/printer/transports';
import type { VoucherOutcome } from '@dash-lib/kioskVouchers';
import type { VoucherLeg } from '@dash-lib/kioskWebOrders';

const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const FIXTURE = path.join(here, '..', '..', 'server', 'tests', 'fixtures', 'kiosk_pricing_parity.json');

type Row = Record<string, unknown>;
type Applied = { promotionId: string; name: string; type: string; applications: number; discountAgorot: number };
type Priced = { lines: SaleLine[]; changes: BasketChange[]; promotions: Applied[]; voucherOutcomes: VoucherOutcome[] };
const noPrinter: Transport = { send: async () => undefined, status: async () => ({ health: 'ok', detail: null }), list: async () => [], dispose: () => undefined };
const r2 = (agorot: number) => Math.round(agorot) / 100;
const SOON = '2026-10-08T13:00';

/** A reachable-less cloud: a goods voucher the basket no longer needs goes back on itself, and that call finds nobody. */
const offline: typeof fetch = async () => {
  throw new TypeError('fetch failed');
};

describe.runIf(existsSync(FIXTURE))('the vouchers sections of the corpus (Android engines), through the Windows kiosk', () => {
  const text = existsSync(FIXTURE) ? readFileSync(FIXTURE, 'utf8').replace(/\r\n/g, '\n') : '{"scenarios":[]}';
  const corpus = JSON.parse(text) as Corpus;

  it('has them (discount vouchers, goods vouchers)', () => {
    expect((corpus.vouchers ?? []).length).toBeGreaterThanOrEqual(15);
    expect((corpus.goodsVouchers ?? []).length).toBeGreaterThanOrEqual(8);
  });

  function kiosk(c: { catalog: string; promotions: string[] }) {
    const svc = new KioskService({ dataDir: mkdtempSync(path.join(os.tmpdir(), 'kd-voucher-parity-')), appVersion: '0.3.0', deviceInfo: {}, transport: noPrinter, fetch: offline, downloader: async () => { throw new Error('no media'); } });
    const raw = corpus.catalogs[c.catalog];
    svc.cloud.applyCatalog({ syncType: 'full', products: raw.products, categories: raw.categories, menu: raw.menu, machineCatalog: { mode: 'all' }, serverTime: 'x' });
    svc.cloud.setPromotions(scenarioPromotions(corpus, c), null);
    return svc;
  }

  /** What the Windows screens send for each line the customer could add (the sheet's and the meal window's own rules). */
  function screenLines(cat: KioskCatalogData, basket: CorpusBasketLine[]) {
    const groupsOf = (id: string) => (cat.groups[id] ?? []).map(moneyGroupOf);
    return basket.flatMap((l) => {
      const slots = cat.meals[l.productId];
      if (slots && slots.length > 0) {
        const { chosen, picks, valid } = mealAfter(slots, l, groupsOf);
        const components = slots.flatMap((sl) =>
          chosen[sl.id].map((productId) => ({
            slotId: sl.id,
            productId,
            options: chosenOptions(groupsOf(productId), picks(sl.id, productId)).map((o) => ({ groupId: o.groupId, optionId: o.optionId, qty: o.qty, pre: o.pre })),
          })),
        );
        return valid ? [{ key: l.id, productId: l.productId, qty: l.qty, notes: [], options: [], meal: { components } }] : [];
      }
      const groups = groupsOf(l.productId);
      const picks = picksAfter(groups, l.ops);
      const options = chosenOptions(groups, picks).map((o) => ({ groupId: o.groupId, optionId: o.optionId, qty: o.qty, pre: o.pre }));
      return picksValid(groups, picks) ? [{ key: l.id, productId: l.productId, qty: l.qty, notes: [], options }] : [];
    });
  }

  function priced(svc: KioskService, c: CorpusVoucherCase | CorpusGoodsCase, now: Date) {
    const cat = (svc as unknown as { catalogData(): KioskCatalogData }).catalogData();
    const input: StartPaymentIn = {
      service: 'take_away', customerName: null, customerPhone: null, tableRef: null,
      tipPct: c.tipPercent, tipAgorot: null,
      lines: screenLines(cat, c.basket) as StartPaymentIn['lines'],
      vouchers: { legs: [], discounts: c.vouchers.map(appliedVoucherOf), saleRef: 'sale-1' },
    };
    return (svc as unknown as { priceBasket(i: StartPaymentIn, now: Date): Priced }).priceBasket(input, now);
  }

  for (const c of corpus.vouchers ?? []) {
    it(`discount: ${c.name}`, () => {
      const svc = kiosk(c);
      try {
        const { lines, changes, promotions, voucherOutcomes } = priced(svc, c, corpusDate(c.now));
        expect(changes).toEqual([]);
        const x = c.expected;
        // What each voucher took, from which lines, and the lines it left out and why.
        expect(voucherOutcomes.length).toBe(x.outcomes.length);
        x.outcomes.forEach((e, i) => {
          const o = voucherOutcomes[i];
          expect(o.voucher.voucherId).toBe(e.voucherId);
          expect(o.amountAgorot, `${e.voucherId} amount`).toBe(e.amountAgorot);
          expect(o.shares, `${e.voucherId} shares`).toEqual(e.shares);
          expect(o.skipped, `${e.voucherId} skipped`).toEqual(e.skipped);
          expect(o.refusal, `${e.voucherId} refusal`).toBe(e.refusal);
        });
        // Each line: the promotion's share (less what gave way to a voucher), the vouchers' share, what it costs.
        for (const e of x.lines) {
          const l = lines.find((y) => y.key === e.id)!;
          expect(
            { unit: unitAgorot(l), gross: lineGross(l), promotion: l.promotionAgorot ?? 0, yielded: l.promotionYieldedAgorot ?? 0, voucher: l.voucherAgorot ?? 0, total: lineGross(l) - (l.promotionAgorot ?? 0) - (l.voucherAgorot ?? 0) },
            `${e.id} line`,
          ).toEqual({ unit: e.unitAgorot, gross: e.grossAgorot, promotion: e.promotionAgorot, yielded: e.promotionYieldedAgorot, voucher: e.voucherAgorot, total: e.totalAgorot });
        }
        expect(promotions).toEqual(x.applied);
        const goods = saleTotals(lines, c.vatRate);
        const tip = tipToCharge({ tipEnabled: c.tipPercent !== null, tipOther: false }, goods.totalAgorot, c.tipPercent, null);
        const totals = saleTotals(lines, c.vatRate, tip);
        expect({ gross: totals.grossAgorot, promotion: totals.discountAgorot - totals.voucherDiscountAgorot, voucher: totals.voucherDiscountAgorot, total: totals.totalAgorot, net: totals.netAgorot, vat: totals.vatAgorot, tip: totals.tipAgorot, due: totals.chargeAgorot, items: lines.reduce((s, l) => s + l.qty, 0) }).toEqual({
          gross: x.grossAgorot, promotion: x.promotionAgorot, voucher: x.voucherAgorot, total: x.totalAgorot, net: x.netAgorot, vat: x.vatAgorot, tip: x.tipAgorot, due: x.dueAgorot, items: x.itemCount,
        });
        if (lines.length === 0) return;

        // The fiscal document: what the Android till's push payload carries for the same sale.
        const wire = documentWire(draft(lines, promotions, totals, { voucherDiscounts: docVoucherDiscounts(voucherOutcomes) }));
        const d = x.document;
        expect({ documentDiscount: wire.documentDiscount ?? null, netAmount: wire.netAmount, vatAmount: wire.vatAmount, tipAmount: wire.tipAmount }).toEqual({
          documentDiscount: d.documentDiscount, netAmount: d.netAmount, vatAmount: d.vatAmount, tipAmount: d.tipAmount,
        });
        expect((wire.promotions as Row[] | undefined) ?? null).toEqual(d.promotions);
        const items = wire.items as Row[];
        expect(items.map((item, i) => ({ id: lines[i].key, promotionDiscount: item.promotionDiscount ?? null, promotionId: item.promotionId ?? null, voucherDiscount: item.voucherDiscount ?? null }))).toEqual(d.items);
        // The vouchers on the document, their lines named by the item's id (here the document's own, mapped back to the basket's key).
        const keyOf = (itemId: string) => lines[ITEM_IDS.indexOf(itemId)]?.key;
        const named = ((wire.voucherDiscounts as Row[] | undefined) ?? []).map((v) => ({ ...v, lines: (v.lines as Array<{ itemId: string; amount: number }>).map((l) => ({ itemId: keyOf(l.itemId), amount: l.amount })) }));
        expect(named.length > 0 ? named : null).toEqual(d.voucherDiscounts);
        // A discount is never a tender: the card pays the whole of what is left.
        expect(((wire.payments as Row[])[0] as Row).amount).toBe(r2(totals.totalAgorot));
        expect(((wire.payments as Row[])[0] as Row).method).toBe('card');
      } finally {
        svc.stop();
      }
    });
  }

  for (const c of (corpus.goodsVouchers ?? []) as CorpusGoodsCase[]) {
    it(`goods leg: ${c.name}`, () => {
      const svc = kiosk(c);
      try {
        const { lines } = priced(svc, c, corpusDate(SOON));
        const goods = saleTotals(lines, 0.18);
        const tip = tipToCharge({ tipEnabled: c.tipPercent !== null, tipOther: false }, goods.totalAgorot, c.tipPercent, null);
        const taken: VoucherLeg[] = c.legs.map((l) => ({
          redemptionId: `r${l.serial}`, serial: l.serial, amountAgorot: 0, eventName: null, includeExtras: l.includeExtras,
          redeemed: l.redeemed.map(([productId, quantity]) => ({ productId, tillProductId: null, name: null, quantity })),
        }));
        const { legs, marks } = (svc as unknown as { legsOf(l: SaleLine[], t: VoucherLeg[]): { legs: DocVoucherLeg[]; marks: Map<string, string> } }).legsOf(lines, taken);
        const x = c.expected;
        // What each voucher is worth against the basket as it stands (a voucher that covers nothing is no leg at all: it goes back).
        expect(legs.map((l) => ({ serial: l.serial, amountAgorot: l.amountAgorot }))).toEqual(x.legs.filter((l) => l.amountAgorot > 0).map((l) => ({ serial: l.serial, amountAgorot: l.amountAgorot })));
        // The marks the covered lines carry on the document ("כלול בשובר #7 (1)").
        const wanted = Object.fromEntries(Object.entries(x.notes).filter(([, v]) => v !== null));
        expect(Object.fromEntries(marks)).toEqual(wanted);
        const goodsTotal = goods.totalAgorot;
        expect(goodsTotal).toBe(x.totalAgorot);
        expect(tip).toBe(x.tipAgorot);
        const paidByLegs = legs.reduce((s, l) => s + l.amountAgorot, 0);
        const principal = Math.max(0, goodsTotal - paidByLegs);
        expect(principal).toBe(x.goodsDueAgorot);
        // What the card is asked: the goods the legs left and the tip.
        expect(principal + tip).toBe(x.dueAgorot);

        // The document: the legs as `production_voucher` payments first, then the card for the rest; the marks on the lines' notes.
        for (const l of lines) {
          const mark = marks.get(l.key);
          if (mark) l.voucherMark = mark;
        }
        const totals = saleTotals(lines, 0.18, tip);
        const wire = documentWire(draft(lines, [], totals, { voucherLegs: legs, card: principal + tip > 0 ? 'visa' : null }));
        const payments = wire.payments as Array<{ method: string; amount: number }>;
        expect(payments.map((p) => [p.method, p.amount])).toEqual([
          ...legs.map((l) => ['production_voucher', r2(l.amountAgorot)]),
          // A card charged for the tip alone still has its leg (the terminal's record), at 0: the tip rides in `tipAmount`.
          ...(principal + tip > 0 ? [['card', r2(principal)]] : []),
        ]);
        // The cloud refuses payments that do not add up to the goods.
        expect(Math.round(payments.reduce((s, p) => s + p.amount * 100, 0))).toBe(totals.totalAgorot);
        const noted = Object.fromEntries((wire.items as Row[]).map((item, i) => [lines[i].key, (item.notes as string | undefined) ?? null]));
        for (const [key, note] of Object.entries(x.notes)) expect(noted[key]?.split(' · ')[0] ?? null, `${key} note`).toBe(note);
        expect(wire.paymentMethod).toBe(legs.length > 0 && principal + tip === 0 ? 'production_voucher' : 'card');
      } finally {
        svc.stop();
      }
    });
  }
});

const ITEM_IDS: string[] = Array.from({ length: 20 }, (_, i) => `00000000-0000-4000-8000-0000000000${String(i).padStart(2, '0')}`);

function draft(
  lines: SaleLine[],
  promotions: Applied[],
  totals: ReturnType<typeof saleTotals>,
  over: { voucherDiscounts?: DocDraft['voucherDiscounts']; voucherLegs?: DocDraft['voucherLegs']; card?: 'visa' | null } = {},
): DocDraft {
  const card = over.card === null ? null : ({ brand: 'visa', last4: '1', authNum: '1', uid: 'u', payments: null, firstPaymentAgorot: null, chargedAgorot: totals.chargeAgorot, meta: {} } as unknown as DocDraft['card']);
  return {
    id: '00000000-0000-4000-8000-000000000001',
    documentType: 320,
    number: 1,
    prefix: null,
    status: 'completed',
    createdAt: '',
    updatedAt: '',
    shiftId: 's',
    businessDate: '2026-10-08',
    cashierId: 'kiosk:m',
    cashierName: 'קיוסק',
    branchId: null,
    orderId: null,
    lines,
    itemIds: lines.map((_, i) => ITEM_IDS[i]),
    tracked: [],
    totals,
    promotions,
    ...(over.voucherDiscounts ? { voucherDiscounts: over.voucherDiscounts } : {}),
    ...(over.voucherLegs ? { voucherLegs: over.voucherLegs } : {}),
    card,
    paymentId: 'p',
    voidMeta: null,
  };
}
