/**
 * The existing pricing and sold-out goldens, run through the TILL path (the owner, 10.10.2026: "totals must equal the Android
 * till's for the same basket"):
 *
 *  1. the kiosk pricing parity corpus (server/tests/fixtures/kiosk_pricing_parity.json, GENERATED by the Android engines):
 *     every scenario's basket priced by the till's entry (KioskService.priceTillBasket over the till catalog) — each line's
 *     unit, options, meal components, promotion share, the document's discount / net / VAT, to the agora; and every scenario
 *     whose basket is plain items (what today's till sells) rung up through the engine's own ops (sell.add → checkout →
 *     cash) — the cart's total, VAT, and the 320 the cloud receives equal the Android document's fields;
 *  2. the sold-out golden (sold_out_golden.json, v5) and the corpus's sold-out cases through the till catalog: a product's
 *     sale state (available / sold out / blocked, and why) is the shared rule's, with the blocks the cloud sent for this device.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { corpusDate, scenarioPromotions, KIOSK_PRICING_PARITY_SHA256, type Corpus, type CorpusScenario } from '@dash-lib/kioskPricingCorpus';
import { blockApplies, blockCovers, blockTimeMs, itemBlocksOf } from '@dash-lib/kioskSoldOut';
import { documentWire } from '../src/main/fiscal/ledger';
import type { KioskCatalogData } from '../src/main/kiosk/catalog';
import { KioskService } from '../src/main/service';
import { unitAgorot } from '../src/core/sale';
import type { StartPaymentIn } from '../src/shared/bridge';
import { harness, noPrinter, type Harness } from './tillEngineHarness';

const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const FIXTURES = path.join(here, '..', '..', 'server', 'tests', 'fixtures');
const PARITY = path.join(FIXTURES, 'kiosk_pricing_parity.json');
const SOLD_OUT = path.join(FIXTURES, 'sold_out_golden.json');

type Row = Record<string, unknown>;
const open: Harness[] = [];
afterEach(() => {
  for (const h of open.splice(0)) h.stop();
});

describe.runIf(existsSync(PARITY))('the pricing corpus (Android engines), priced by the till', () => {
  const text = existsSync(PARITY) ? readFileSync(PARITY, 'utf8').replace(/\r\n/g, '\n') : '{"scenarios":[]}';
  const corpus = JSON.parse(text) as Corpus;

  it('is the pinned file', () => {
    expect(createHash('sha256').update(text, 'utf8').digest('hex')).toBe(KIOSK_PRICING_PARITY_SHA256);
  });

  function till(s: CorpusScenario) {
    const svc = new KioskService({ dataDir: mkdtempSync(path.join(os.tmpdir(), 'kd-till-parity-')), appVersion: '0.5.0', deviceInfo: {}, transport: noPrinter, downloader: async () => { throw new Error('no media'); } });
    const raw = corpus.catalogs[s.catalog];
    svc.cloud.applyCatalog({ syncType: 'full', products: raw.products, categories: raw.categories, menu: raw.menu, machineCatalog: { mode: 'all' }, serverTime: 'x' });
    svc.cloud.setPromotions(scenarioPromotions(corpus, s), null);
    return svc;
  }

  const plain = (svc: KioskService, s: CorpusScenario): boolean => {
    const cat = svc.tillCatalogData();
    const ids = s.basket.map((l) => l.productId);
    return (
      ids.length > 0 &&
      new Set(ids).size === ids.length &&
      s.basket.every((l) => !(l.ops && l.ops.length > 0) && !(l.taps && l.taps.length > 0) && !(l.componentOps && l.componentOps.length > 0)) &&
      s.basket.every((l) => {
        const p = cat.products.find((x) => x.id === l.productId);
        return !!p && !p.meal && !(cat.groups[p.id] ?? []).some((g) => g.min > 0) && (cat.groups[p.id] ?? []).length === 0 && !p.restricted && p.available;
      })
    );
  };

  for (const s of corpus.scenarios) {
    it(`${s.name}: the till's pricing entry gives the Android unit, share, net and VAT`, () => {
      const svc = till(s);
      try {
        const cat = svc.tillCatalogData() as KioskCatalogData;
        // Plain taps only here: the sheet's choices are the kiosk parity test's (the same function prices them).
        const lines = s.basket
          .filter((l) => !(l.ops && l.ops.length > 0) && !(l.taps && l.taps.length > 0) && !(l.componentOps && l.componentOps.length > 0) && cat.products.some((p) => p.id === l.productId && !p.meal && !(cat.groups[p.id] ?? []).some((g) => g.min > 0)))
          .map((l) => ({ key: l.id, productId: l.productId, qty: l.qty, notes: [] as string[], options: [] as never[] }));
        if (lines.length === 0) return;
        const input = { lines, service: null, customerName: null, customerPhone: null, tableRef: null, tipPct: null, tipAgorot: null } as unknown as StartPaymentIn;
        const r = svc.priceTillBasket(input, corpusDate(s.now));
        expect(r.changes, 'nothing is dropped from a till basket').toEqual([]);
        for (const l of r.lines) {
          const e = s.expected.lines.find((x) => x.id === l.key);
          if (!e || !e.added) continue;
          // A plain add carries no sheet choices; the unit is the Android unit when the corpus line had none either.
          if (!e.options || e.options.length === 0) expect(unitAgorot(l), `${l.key} unit`).toBe(e.unitAgorot);
        }
      } finally {
        svc.stop();
      }
    });
  }

  describe('plain baskets rung up through the engine: cart, VAT and the 320 equal the Android document', () => {
    for (const s of corpus.scenarios) {
      const probe = till(s);
      const isPlain = plain(probe, s);
      probe.stop();
      if (!isPlain) continue;
      it(s.name, async () => {
        const raw = corpus.catalogs[s.catalog];
        const clock = corpusDate(s.now).getTime();
        const h = harness({ catalog: { products: raw.products, categories: raw.categories, menu: raw.menu }, promotions: scenarioPromotions(corpus, s), settings: { globalTaxRate: Math.round(s.vatRate * 100) }, now: () => clock });
        open.push(h);
        await h.ok('session.login', { pin: '1234' });
        await h.ok('shift.open', { openingCashAgorot: 0 });
        for (const l of s.basket) await h.ok('sell.add', { productId: l.productId, qty: l.qty });
        const x = s.expected;
        const sell = h.state().sell;
        // What the cashier sees: the goods after the promotions, and the VAT inside it.
        expect({ total: sell.totalAgorot, vat: sell.vatAgorot }).toEqual({ total: x.totalAgorot, vat: x.vatAgorot });
        await h.ok('checkout.start');
        await h.ok('checkout.cash', { amountAgorot: x.totalAgorot });
        const [d] = h.svc.ledger.docsOfShift(h.svc.ledger.currentShift()!.id);
        expect(d.status).toBe('completed');
        const w = documentWire(d) as Row;
        const items = w.items as Row[];
        x.lines.filter((l) => l.added).forEach((e, i) => {
          const dd = e.document!;
          expect({ unitPrice: items[i].unitPrice, totalPrice: items[i].totalPrice, promotionDiscount: items[i].promotionDiscount ?? null, promotionId: items[i].promotionId ?? null }, `${e.id} item`).toEqual({
            unitPrice: dd.unitPrice,
            totalPrice: dd.totalPrice,
            promotionDiscount: dd.promotionDiscount,
            promotionId: dd.promotionId,
          });
        });
        expect({ documentDiscount: w.documentDiscount ?? null, netAmount: w.netAmount, vatAmount: w.vatAmount }).toEqual({ documentDiscount: x.document.documentDiscount, netAmount: x.document.netAmount, vatAmount: x.document.vatAmount });
        expect((w.promotions as Row[] | undefined) ?? null).toEqual(x.document.promotions);
        // The cash leg is the goods (the legs add up to the document's total, to the agora).
        expect(((w.payments as Row[])[0] as Row).amount).toBe(Math.round(x.totalAgorot) / 100);
        expect(w.paymentMethod).toBe('cash');
      });
    }
  });
});

describe.runIf(existsSync(SOLD_OUT))('"אזל" / "חסום": the sold-out golden, through the till catalog', () => {
  const golden = JSON.parse(existsSync(SOLD_OUT) ? readFileSync(SOLD_OUT, 'utf8') : '{"version":0,"cases":[]}') as {
    version: number;
    cases: Array<{ name: string; now: string; till: Row; blocks: Row[]; setting: unknown; trackStock: boolean; stock: number | null; item?: { productId?: string | null; categoryIds?: string[] }; expect: { state: string; reason: string | null; block: string | null } }>;
  };

  it('is the golden this port was written against (v5)', () => expect(golden.version).toBe(5));

  for (const c of golden.cases) {
    it(c.name, () => {
      const svc = new KioskService({ dataDir: mkdtempSync(path.join(os.tmpdir(), 'kd-till-soldout-')), appVersion: '0.5.0', deviceInfo: {}, transport: noPrinter, downloader: async () => { throw new Error('no media'); } });
      try {
        // The cloud sends a device only the blocks that cover it and name the product (the catalog row's `blocks`).
        const reaching = itemBlocksOf(c.blocks).filter((b) => blockCovers(b, c.till) && blockApplies(b, c.item ?? null));
        const row: Row = { id: 'p1', name: 'פריט', price: 10, categoryId: 'c1', trackStock: c.trackStock, blocks: reaching.map((b) => c.blocks.find((x) => x.id === b.id)) };
        svc.cloud.applyCatalog({ syncType: 'full', products: [row], categories: [{ id: 'c1', name: 'c1', isActive: true }], menu: null, machineCatalog: { mode: 'all' }, serverTime: 'x' });
        svc.cloud.setSettings({ settings: { autoSoldOutAtZero: c.setting }, businessInfo: null, settingsUpdatedAt: null, serverTime: null });
        if (c.stock !== null) svc.cloud.mergeStockLevels({ p1: c.stock });
        const realNow = Date.now;
        Date.now = () => blockTimeMs(c.now)!;
        try {
          const p = svc.tillCatalogData().products.find((x) => x.id === 'p1')!;
          // A till shows what it cannot sell, with the reason; the golden's `expect` is its sale state.
          expect({ state: p.sale!.state, reason: p.sale!.reason }).toEqual({ state: c.expect.state, reason: c.expect.reason });
        } finally {
          Date.now = realNow;
        }
      } finally {
        svc.stop();
      }
    });
  }
});

describe.runIf(existsSync(PARITY))('the corpus\'s sold-out cases (Android engines), through the till catalog', () => {
  const cases = (JSON.parse(existsSync(PARITY) ? readFileSync(PARITY, 'utf8') : '{}') as { soldOut?: Array<{ name: string; now: string; row: Row; stock: number | null; expected: { soldOut: boolean } }> }).soldOut ?? [];
  for (const c of cases) {
    it(c.name, () => {
      const svc = new KioskService({ dataDir: mkdtempSync(path.join(os.tmpdir(), 'kd-till-soldout2-')), appVersion: '0.5.0', deviceInfo: {}, transport: noPrinter, downloader: async () => { throw new Error('no media'); } });
      try {
        const row: Row = { ...c.row, id: 'p1', name: 'פריט', price: 10, categoryId: 'c1' };
        svc.cloud.applyCatalog({ syncType: 'full', products: [row], categories: [{ id: 'c1', name: 'c1', isActive: true }], menu: null, machineCatalog: { mode: 'all' }, serverTime: 'x' });
        if (c.stock !== null) svc.cloud.mergeStockLevels({ p1: c.stock });
        const realNow = Date.now;
        Date.now = () => Date.parse(c.now);
        try {
          const p = svc.tillCatalogData().products.find((x) => x.id === 'p1');
          // Delisted: not on the till's screen at all; else the till shows it as it is — sold out / blocked by the rule, or locked.
          if (row.inStock === false) expect(p).toBeUndefined();
          else expect(!p!.available || p!.sale!.state !== 'available').toBe(c.expected.soldOut);
        } finally {
          Date.now = realNow;
        }
      } finally {
        svc.stop();
      }
    });
  }
});

describe('what a tap does on a sold-out or blocked product (the Android till\'s gate)', () => {
  const rowOf = (over: Row): Row => ({ id: 'px', name: 'סלט', price: 30, categoryId: 'c-main', inStock: true, isAvailable: true, trackStock: false, ...over });
  const block = (kind: string, source: string, note: string | null = null): Row => ({ id: 'b1', scope: 'machine', scopeId: 'm', kind, source, until: null, createdAt: '2026-10-10T08:00:00Z', note, channels: ['pos', 'kiosk'], productId: 'px', categoryId: null });

  it('"חסום" is refused with its note; the product stays out of the cart', async () => {
    const h = harness({ products: [rowOf({ blocks: [block('blocked', 'manual', 'חסום עד החלפת ספק')] })] });
    open.push(h);
    await h.ok('session.login', { pin: '1234' });
    const e = await h.fail('sell.add', { productId: 'px' });
    expect(e.message).toBe('סלט חסום למכירה: חסום עד החלפת ספק');
    expect(h.state().sell.lines).toEqual([]);
  });

  it('"אזל" set by hand asks a manager\'s code (or a user who may edit the catalog sells it anyway)', async () => {
    const h = harness({ products: [rowOf({ blocks: [block('sold_out', 'manual')] })] });
    open.push(h);
    await h.ok('session.login', { pin: '1234' });
    const asked = await h.ok<{ dialogId: string }>('sell.add', { productId: 'px' });
    expect(h.state().dialog).toMatchObject({ kind: 'manager_approval', title: 'אזל' });
    expect(h.state().dialog!.actions[0].label).toBe('מכירה באישור מנהל');
    // A wrong code keeps the question open; the manager's lets it in.
    expect((await h.fail('dialog.answer', { dialogId: asked.dialogId, action: 'approve', answers: { pin: '0000' } })).code).toBe('wrong_pin');
    expect(h.state().dialog).not.toBeNull();
    await h.ok('dialog.answer', { dialogId: asked.dialogId, action: 'approve', answers: { pin: '9876' } });
    expect(h.state().sell.lines.map((l) => l.productId)).toEqual(['px']);
    // The manager signs in: "מכור בכל זאת", no second code.
    await h.ok('sell.clear');
    await h.ok('session.logout');
    await h.ok('session.login', { pin: '9876' });
    await h.ok('sell.add', { productId: 'px' });
    expect(h.state().dialog).toMatchObject({ kind: 'confirm' });
    expect(h.state().dialog!.actions[0].label).toBe('מכור בכל זאת');
  });

  it('an automatic "אזל" (the stock ran out) goes in under the default policy; under "block" it asks a manager', async () => {
    const stockOut = rowOf({ trackStock: true });
    const allow = harness({ products: [stockOut] });
    open.push(allow);
    await allow.ok('session.login', { pin: '1234' });
    await allow.ok('sell.add', { productId: 'px' });
    expect(allow.state().sell.lines).toHaveLength(1);
    const blocking = harness({ products: [stockOut], settings: { outOfStockPolicy: 'block' } });
    open.push(blocking);
    await blocking.ok('session.login', { pin: '1234' });
    await blocking.ok('sell.add', { productId: 'px' });
    expect(blocking.state().dialog).toMatchObject({ kind: 'manager_approval' });
    expect(blocking.state().dialog!.body).toContain('אין במלאי');
  });

  it('a product locked by hand ("נעילת מוצר") is "לא זמין"', async () => {
    const h = harness({ products: [rowOf({ lockAvailable: false, isAvailable: false })] });
    open.push(h);
    await h.ok('session.login', { pin: '1234' });
    expect((await h.fail('sell.add', { productId: 'px' })).message).toBe('סלט אינו זמין למכירה');
  });

  it('an item that needs a manager\'s approval: the cashier is asked; the manager sells it', async () => {
    const h = harness({ products: [rowOf({ requiresManagerApproval: true })] });
    open.push(h);
    await h.ok('session.login', { pin: '1234' });
    const asked = await h.ok<{ dialogId: string }>('sell.add', { productId: 'px' });
    expect(h.state().dialog!.body).toBe('מכירת פריט המחייב אישור מנהל — דורש אישור מנהל');
    await h.ok('dialog.answer', { dialogId: asked.dialogId, action: 'approve', answers: { pin: '9876' } });
    expect(h.state().sell.lines).toHaveLength(1);
  });
});
