"""
Generate the clients' copies of the kiosk layouts' shared data (docs/SPEC_KIOSK_LAYOUTS.md) from the
golden fixtures in server/tests/fixtures/:

  kiosk_category_icons.json  → server app/services/kiosk_shared/ (same bytes),
                               client src/lib/kioskIconData.ts,
                               pos-android domain/KioskCategoryIconData.kt + src/test/resources (same bytes)
  kiosk_text_registry.json   → server app/services/kiosk_shared/ (same bytes),
                               client src/lib/kioskTextRegistryData.ts,
                               pos-android domain/KioskTextRegistryData.kt + src/test/resources (same bytes)
  kiosk_layout_templates.json → pos-android src/test/resources (same bytes)

pos-android is expected beside pos-server (../../pos-android from this repo's root); it is skipped
when it is not there. Run from anywhere:  python server/scripts/gen_kiosk_layout_data.py
The tests (server tests/test_kiosk_layout.py, client kioskLayout.test.ts, pos-android
KioskLayoutTest) pin the fixtures' SHA-256 and compare every copy.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # pos-server
FIX = ROOT / "server" / "tests" / "fixtures"
SHARED = ROOT / "server" / "app" / "services" / "kiosk_shared"
CLIENT_LIB = ROOT / "client" / "src" / "lib"
ANDROID = ROOT.parent / "pos-android"
ANDROID_DOMAIN = ANDROID / "app" / "src" / "main" / "java" / "il" / "co" / "runnersys" / "pos" / "domain"
ANDROID_TEST_RES = ANDROID / "app" / "src" / "test" / "resources"


def lf_bytes(path: Path) -> bytes:
    return path.read_bytes().replace(b"\r\n", b"\n")


def write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() == data:
        return
    path.write_bytes(data)
    print("wrote", path)


def kt(s: str) -> str:
    """A Kotlin string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


def kt_list(items) -> str:
    return "listOf(" + ", ".join(kt(x) for x in items) + ")"


def ts_header(source: str) -> str:
    return f"// GENERATED by server/scripts/gen_kiosk_layout_data.py from server/tests/fixtures/{source} — do not edit.\n"


def gen_icons() -> None:
    src = FIX / "kiosk_category_icons.json"
    data = lf_bytes(src)
    doc = json.loads(data)
    write(SHARED / "kiosk_category_icons.json", data)
    ts = (
        ts_header("kiosk_category_icons.json")
        + "import type { KioskIconSet } from './kioskIcons';\n\n"
        + "export const KIOSK_ICON_DATA: KioskIconSet = "
        + json.dumps({k: doc[k] for k in ("version", "viewBox", "icons", "cases")}, ensure_ascii=False, indent=2)
        + ";\n"
    )
    write(CLIENT_LIB / "kioskIconData.ts", ts.encode("utf-8"))
    if ANDROID.exists():
        write(ANDROID_TEST_RES / "kiosk_category_icons.json", data)
        rows = []
        for i in doc["icons"]:
            rows.append(
                "        KioskIconDef(\n"
                f"            id = {kt(i['id'])}, labelHe = {kt(i['label']['he'])}, labelEn = {kt(i['label']['en'])}, emoji = {kt(i['emoji'])}, hue = {int(i['hue'])},\n"
                f"            body = {kt_list(i['b'])},\n"
                f"            inner = {kt_list(i['i'])},\n"
                f"            outer = {kt_list(i['o'])},\n"
                f"            keywords = {kt_list(i['keywords']['he'] + i['keywords']['en'])},\n"
                "        ),"
            )
        body = (
            "package il.co.runnersys.pos.domain\n\n"
            "// GENERATED by pos-server server/scripts/gen_kiosk_layout_data.py from tests/fixtures/kiosk_category_icons.json — do not edit.\n\n"
            "/** The built-in category icons (KioskCategoryIcons), the dashboard's kioskIconData.ts path for path. */\n"
            "object KioskCategoryIconData {\n"
            "    val ICONS: List<KioskIconDef> = listOf(\n"
            + "\n".join(rows)
            + "\n    )\n}\n"
        )
        write(ANDROID_DOMAIN / "KioskCategoryIconData.kt", body.encode("utf-8"))


def gen_registry() -> None:
    src = FIX / "kiosk_text_registry.json"
    data = lf_bytes(src)
    doc = json.loads(data)
    write(SHARED / "kiosk_text_registry.json", data)
    ts = (
        ts_header("kiosk_text_registry.json")
        + "import type { KioskTextRegistry } from './kioskTexts';\n\n"
        + "export const KIOSK_TEXT_REGISTRY_DATA: KioskTextRegistry = "
        + json.dumps(doc, ensure_ascii=False, indent=2)
        + ";\n"
    )
    write(CLIENT_LIB / "kioskTextRegistryData.ts", ts.encode("utf-8"))
    if ANDROID.exists():
        write(ANDROID_TEST_RES / "kiosk_text_registry.json", data)
        rows = [
            f"        KioskTextEntry({kt(t['key'])}, {kt(t['group'])}, {kt_list(t.get('android') or [])}, {kt_list(t.get('placeholders') or [])}),"
            for t in doc["texts"]
        ]
        body = (
            "package il.co.runnersys.pos.domain\n\n"
            "// GENERATED by pos-server server/scripts/gen_kiosk_layout_data.py from tests/fixtures/kiosk_text_registry.json — do not edit.\n\n"
            "/** The text registry as the till needs it: each text's key, group, Android strings and named placeholders (KioskTextRegistry). */\n"
            "object KioskTextRegistryData {\n"
            "    val ENTRIES: List<KioskTextEntry> = listOf(\n"
            + "\n".join(rows)
            + "\n    )\n}\n"
        )
        write(ANDROID_DOMAIN / "KioskTextRegistryData.kt", body.encode("utf-8"))


def gen_templates() -> None:
    data = lf_bytes(FIX / "kiosk_layout_templates.json")
    if ANDROID.exists():
        write(ANDROID_TEST_RES / "kiosk_layout_templates.json", data)


if __name__ == "__main__":
    for name in ("kiosk_layout_templates.json", "kiosk_category_icons.json", "kiosk_text_registry.json"):
        p = FIX / name
        if p.exists():
            print(name, hashlib.sha256(lf_bytes(p)).hexdigest())
    gen_templates()
    if (FIX / "kiosk_category_icons.json").exists():
        gen_icons()
    if (FIX / "kiosk_text_registry.json").exists():
        gen_registry()
