"""
The kiosk pricing parity corpus (tests/fixtures/kiosk_pricing_parity.json) on the cloud's side.

The corpus is GENERATED by running the Android kiosk's engines over a scenario list (pos-android
app/src/test/.../KioskPricingCorpusTest.kt, the same file in app/src/test/resources); the Windows and
the browser kiosk replay every scenario through their one TypeScript port (client
lib/kioskPricingParity.test.ts, kiosk-desktop test/kioskPricingParity.test.ts). Here, that what the
kiosks document for those sales is what the cloud takes as it stands:

  - the file is the pinned one (the same SHA-256 constant in all four tests);
  - every sale's document — the Windows kiosk's wire (kiosk_desktop/transaction_card_sale_320.json)
    with the corpus's items, promotion shares, discount, VAT and tip — validates, its card leg
    reconciles with the goods after promotions, its net and VAT add up;
  - the cloud's own twin of the choice rules (app/services/menu.py `price_picks`, which checks what a
    till sends) charges every dish's choices as the Android kiosk did.
"""
import copy
import hashlib
import json
from decimal import Decimal
from pathlib import Path

import pytest

from app.schemas.transaction import TransactionsBatchEnvelope
from app.services import menu as MENU
from app.services.tenders import expected_tender_total, reconciliation_error
from app.services.transactions import validate_documents

FIXTURES = Path(__file__).parent / "fixtures"
CORPUS = FIXTURES / "kiosk_pricing_parity.json"
#: The corpus's SHA-256 (LF) — the same constant as pos-android KioskPricingCorpusTest.GOLDEN_SHA256 and
#: client lib/kioskPricingCorpus.ts KIOSK_PRICING_PARITY_SHA256. Regenerate, never edit by hand.
CORPUS_SHA256 = "2448b069922eb90575a9db7590595bdc20d2115634a1f78ae7627d84703a82e6"


def _text() -> str:
    return CORPUS.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _corpus() -> dict:
    return json.loads(_text())


def _sales():
    return [s for s in _corpus()["scenarios"] if any(l["added"] for l in s["expected"]["lines"])]


def test_the_corpus_is_the_pinned_one():
    corpus = _corpus()
    assert corpus["format"] == "kiosk-pricing-parity/1"
    assert len(corpus["scenarios"]) >= 60
    assert hashlib.sha256(_text().encode("utf-8")).hexdigest() == CORPUS_SHA256


def _document(s: dict) -> dict:
    """The Windows kiosk's card sale (its contract fixture) carrying this scenario's sale."""
    env = json.loads((FIXTURES / "kiosk_desktop" / "transaction_card_sale_320.json").read_text(encoding="utf-8"))
    tx = env["transactions"][0]
    tx.pop("stockMovements", None)
    x = s["expected"]
    items = []
    for i, line in enumerate(l for l in x["lines"] if l["added"]):
        d = line["document"]
        item = {
            "id": f"0b1c2d3e-0000-4000-8000-{i:012d}",
            "productName": line["id"],
            "quantity": line["qty"],
            "unitPrice": d["unitPrice"],
            "totalPrice": d["totalPrice"],
            "transactionType": 2,
        }
        if d["promotionDiscount"] is not None:
            item["promotionDiscount"] = d["promotionDiscount"]
            item["promotionId"] = d["promotionId"]
        if d["details"] is not None:
            item["details"] = d["details"]
        items.append(item)
    goods = Decimal(x["totalAgorot"]) / 100
    tx.update(
        items=items,
        totalAmount=float(Decimal(x["grossAgorot"]) / 100),
        documentDiscount=x["document"]["documentDiscount"],
        netAmount=x["document"]["netAmount"],
        vatAmount=x["document"]["vatAmount"],
        vatRate=s["vatRate"],
        tipAmount=x["document"]["tipAmount"],
        promotions=x["document"]["promotions"] or [],
    )
    tx["payments"] = [dict(copy.deepcopy(tx["payments"][0]), amount=float(goods))]
    return env


@pytest.mark.parametrize("s", _sales(), ids=lambda s: s["name"][:60])
def test_every_kiosk_sale_is_a_document_the_cloud_takes_as_it_stands(s):
    env = TransactionsBatchEnvelope.model_validate(_document(s))
    valid, rejected, unidentified = validate_documents(env.transactions)
    assert rejected == [] and unidentified == []
    (_, tx, warnings), = valid
    assert warnings == []
    x = s["expected"]
    # The items add up to the document; the promotions are its discount, line by line.
    assert sum(Decimal(str(i.total_price)) for i in tx.items) == Decimal(x["grossAgorot"]) / 100
    shares = sum(Decimal(str(i.promotion_discount or 0)) for i in tx.items)
    assert shares == Decimal(x["promotionAgorot"]) / 100 == Decimal(str(tx.document_discount or 0))
    # The card leg: the goods after promotions; the tip beside it, never in it.
    expected = expected_tender_total(
        total_amount=tx.total_amount,
        document_discount=tx.document_discount,
        document_type=tx.document_type,
        refund_of_transaction_id=tx.refund_of_transaction_id,
    )
    assert reconciliation_error(expected, [p.amount for p in tx.payments]) is None
    # VAT once per document, prices include it.
    assert Decimal(str(tx.net_amount)) + Decimal(str(tx.vat_amount)) == Decimal(x["totalAgorot"]) / 100


def _rules(group: dict) -> MENU.GroupRules:
    options = group.get("options") or []
    return MENU.GroupRules(
        min_select=group.get("minSelect") or 0,
        max_select=group.get("maxSelect"),
        free_count=group.get("freeCount") or 0,
        allow_quantity=bool(group.get("allowQuantity")),
        allow_pre=bool(group.get("allowPre")),
        prices={o["id"]: MENU._agorot(o.get("price")) for o in options},
        limits={o["id"]: o["maxQty"] for o in options if o.get("maxQty")},
    )


def _choice_cases():
    corpus = _corpus()
    out = []
    for s in corpus["scenarios"]:
        groups = {g["id"]: g for g in corpus["catalogs"][s["catalog"]]["menu"]["groups"]}
        for line in s["expected"]["lines"]:
            if line.get("options"):
                out.append((f'{s["name"][:40]}/{line["id"]}', groups, line["options"], line["added"]))
    return out


@pytest.mark.parametrize("case", _choice_cases(), ids=lambda c: c[0])
def test_the_clouds_choice_rules_charge_what_the_kiosk_charged(case):
    _, groups, options, added = case
    by_group: dict = {}
    for o in options:
        by_group.setdefault(o["groupId"], []).append(o)
    for gid, picks in by_group.items():
        rules = _rules(groups[gid])
        cloud = [MENU.Pick(option_id=p["optionId"], qty=p["qty"], pre=p["pre"]) for p in picks]
        assert MENU.price_picks(rules, cloud) == [p["chargedAgorot"] for p in picks]
        if added:
            assert MENU.validate_picks(rules, cloud) == []
